//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_nhan_su
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luong()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaLuong { get; set; }
        public Nullable<int> LuongCB { get; set; }
        public Nullable<double> HSLuong { get; set; }
        public Nullable<double> HSPhuCap { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHTN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
