//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_nhan_su
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        public string Taikhoan { get; set; }
        public string matkhau { get; set; }
    }
}
