//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_nhan_su
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiNhanSuEntities : DbContext
    {
        public QuanLiNhanSuEntities()
            : base("name=QuanLiNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoHiem> BaoHiems { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<Luong> Luongs { get; set; }
        public virtual DbSet<Nguoidung> Nguoidungs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrinhDoHV> TrinhDoHVs { get; set; }
    
        [DbFunction("QuanLiNhanSuEntities", "DanhsachNV")]
        public virtual IQueryable<DanhsachNV_Result> DanhsachNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DanhsachNV_Result>("[QuanLiNhanSuEntities].[DanhsachNV]()");
        }
    
        [DbFunction("QuanLiNhanSuEntities", "DanhsachNV1")]
        public virtual IQueryable<DanhsachNV1_Result> DanhsachNV1(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DanhsachNV1_Result>("[QuanLiNhanSuEntities].[DanhsachNV1](@ma)", maParameter);
        }
    
        [DbFunction("QuanLiNhanSuEntities", "NhanVienhopdong")]
        public virtual IQueryable<NhanVienhopdong_Result> NhanVienhopdong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<NhanVienhopdong_Result>("[QuanLiNhanSuEntities].[NhanVienhopdong]()");
        }
    
        [DbFunction("QuanLiNhanSuEntities", "Nhanvienlaunam")]
        public virtual IQueryable<Nhanvienlaunam_Result> Nhanvienlaunam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nhanvienlaunam_Result>("[QuanLiNhanSuEntities].[Nhanvienlaunam]()");
        }
    
        [DbFunction("QuanLiNhanSuEntities", "Nhanvienmoi")]
        public virtual IQueryable<Nhanvienmoi_Result> Nhanvienmoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nhanvienmoi_Result>("[QuanLiNhanSuEntities].[Nhanvienmoi]()");
        }
    
        [DbFunction("QuanLiNhanSuEntities", "Nhanvienphongban")]
        public virtual IQueryable<Nhanvienphongban_Result> Nhanvienphongban(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nhanvienphongban_Result>("[QuanLiNhanSuEntities].[Nhanvienphongban](@ten)", tenParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sua(string hoten, string tenpb, string chucvu, Nullable<int> luong, string quequan)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var quequanParameter = quequan != null ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua", hotenParameter, tenpbParameter, chucvuParameter, luongParameter, quequanParameter);
        }
    
        public virtual int thaydoiluong(string ma, Nullable<int> luongcb, Nullable<double> hsluong, Nullable<double> hspc, Nullable<double> bhyt, Nullable<double> bhxh, Nullable<double> bhtn)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var luongcbParameter = luongcb.HasValue ?
                new ObjectParameter("luongcb", luongcb) :
                new ObjectParameter("luongcb", typeof(int));
    
            var hsluongParameter = hsluong.HasValue ?
                new ObjectParameter("hsluong", hsluong) :
                new ObjectParameter("hsluong", typeof(double));
    
            var hspcParameter = hspc.HasValue ?
                new ObjectParameter("hspc", hspc) :
                new ObjectParameter("hspc", typeof(double));
    
            var bhytParameter = bhyt.HasValue ?
                new ObjectParameter("bhyt", bhyt) :
                new ObjectParameter("bhyt", typeof(double));
    
            var bhxhParameter = bhxh.HasValue ?
                new ObjectParameter("bhxh", bhxh) :
                new ObjectParameter("bhxh", typeof(double));
    
            var bhtnParameter = bhtn.HasValue ?
                new ObjectParameter("bhtn", bhtn) :
                new ObjectParameter("bhtn", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("thaydoiluong", maParameter, luongcbParameter, hsluongParameter, hspcParameter, bhytParameter, bhxhParameter, bhtnParameter);
        }
    
        public virtual int xoanv(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoanv", maParameter);
        }
    
        public virtual int xoapb(string tenpb)
        {
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoapb", tenpbParameter);
        }
    }
}
